# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

author:
  name: Diego C. Sampaio
  email: "slavelix@ymail.com"

title: O branco da minha janela
email: slavelix@ymail.com
description: >- # this means to ignore newlines until "baseurl:"
  Um blog para falar de todo um caleidoscópio de assuntos que
  interessam, desde a origem do "n" oculto na palavra "muito",
  que todo mundo pronuncia "muinto", até o atual estado da
  ciência de fusão nuclear. No meio, uns contos, umas crônicas,
  uns pseudo poemas horríveis...

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: true
excerpt_separator: <!--more-->

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima

header_pages:
  - page_fictions.markdown
  - page_technology.markdown
  - page_rpg.markdown  
  - page_about.markdown    

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/kriptolix" }
    - { platform: mastodon, user_url: "https://ursal.zone/@Kriptolix" }   

collections:
  fictions:
    output: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
